services:
  - type: web
    name: rudhra-bot
    repo: https://github.com/rudhachu/testw.git
    branch: master
    env: docker
    dockerfilePath: lib/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
